# Local type stubs for the slice of atheris this project uses (the package ships no type information).
from collections.abc import Callable
from contextlib import AbstractContextManager

def Setup(args: list[str], test_one_input: Callable[[bytes], None]) -> list[str]: ...
def Fuzz() -> None: ...
def instrument_imports() -> AbstractContextManager[None]: ...
