# Local type stubs for the slice of feedgen this project uses (the package ships no type information).
from collections.abc import Mapping
from datetime import datetime

class MediaEntryExtension:
    def thumbnail(
        self, thumbnail: Mapping[str, str] | None = None, group: str = "default", replace: bool = False
    ) -> None: ...

class FeedEntry:
    # Added by FeedGenerator.load_extension("media"); declared here because feedserver always loads it.
    media: MediaEntryExtension

    def id(self, id: str | None = None) -> str: ...
    def title(self, title: str | None = None) -> str: ...
    def link(self, link: None = None, replace: bool = False, *, href: str, rel: str = ...) -> None: ...
    def author(self, author: None = None, replace: bool = False, *, name: str) -> None: ...
    def updated(self, updated: datetime | None = None) -> datetime: ...
    def published(self, published: datetime | None = None) -> datetime: ...
    def content(
        self, content: str | None = None, src: str | None = None, type: str | None = None
    ) -> None: ...
