# Local type stubs for the slice of feedgen this project uses (the package ships no type information).
from datetime import datetime

from feedgen.entry import FeedEntry

class FeedGenerator:
    def id(self, id: str | None = None) -> str: ...
    def title(self, title: str | None = None) -> str: ...
    def link(self, link: None = None, replace: bool = False, *, href: str, rel: str = ...) -> None: ...
    def updated(self, updated: datetime | None = None) -> datetime: ...
    def load_extension(self, name: str, atom: bool = True, rss: bool = True) -> None: ...
    def add_entry(self, feedEntry: FeedEntry | None = None, order: str = "prepend") -> FeedEntry: ...
    def atom_str(
        self,
        pretty: bool = False,
        extensions: bool = True,
        encoding: str = "UTF-8",
        xml_declaration: bool = True,
    ) -> bytes: ...
