# Local type stubs for the slice of adbutils this project uses (the package ships no type information).
class AdbError(Exception): ...
class AdbTimeout(AdbError): ...

class AdbClient:
    def connect(self, addr: str, timeout: float | None = None) -> str: ...

adb: AdbClient

def adb_path() -> str: ...
