"""The device the scraper drives, as a structural type: the slice of uiautomator2's Device and UiObject
this project calls. Code takes a `Device` rather than `uiautomator2.Device`, so the real connection
and tests/fakedevice.py's scripted stand-in are both accepted without any cast. These are also the
only declarations of it: the local stub typings/uiautomator2 types `connect()` as returning this
`Device`, so a method added here is one the real uiautomator2 Device has to have."""

from collections.abc import Mapping
from typing import Protocol

from PIL import Image


class ShellOutput(Protocol):
    @property
    def output(self) -> str: ...


class Selector(Protocol):
    """What `device(text=...)`, `device(resourceIdMatches=...)` and friends return."""

    def exists(self, timeout: float = 0) -> bool: ...
    @property
    def count(self) -> int: ...
    @property
    def info(self) -> Mapping[str, Mapping[str, int]]: ...
    def __getitem__(self, instance: int) -> Selector: ...
    def click(self, timeout: float | None = None) -> None: ...
    def set_text(self, text: str, timeout: float | None = None) -> None: ...


class Device(Protocol):
    def __call__(self, **kwargs: str | list[str]) -> Selector: ...
    @property
    def info(self) -> Mapping[str, str | int | bool | None]: ...
    @property
    def clipboard(self) -> str | None: ...
    def dump_hierarchy(self) -> str: ...
    def screenshot(self) -> Image.Image: ...
    def window_size(self) -> tuple[int, int]: ...
    def implicitly_wait(self, seconds: float | None = None) -> float: ...
    def app_list(self) -> list[str]: ...
    def app_current(self) -> Mapping[str, str]: ...
    def app_start(self, package_name: str, activity: str | None = None, stop: bool = False) -> None: ...
    def shell(self, cmdargs: str | list[str], timeout: float = 60) -> ShellOutput: ...
    def press(self, key: str) -> None: ...
    def swipe(self, fx: int, fy: int, tx: int, ty: int, duration: float | None = None) -> None: ...
    def click(self, x: int, y: int) -> None: ...
