# Local type stubs for the slice of uiautomator2 this project uses (the package ships no type
# information). Only what the scraper calls is declared; the runtime has much more.
from collections.abc import Mapping

from PIL import Image

class ShellResponse:
    output: str
    exit_code: int

class UiObject:
    # At runtime `exists` is a property returning a callable; calling it is all this project does.
    def exists(self, timeout: float = 0) -> bool: ...
    @property
    def count(self) -> int: ...
    @property
    def info(self) -> Mapping[str, Mapping[str, int]]: ...
    def __getitem__(self, instance: int) -> UiObject: ...
    def click(self, timeout: float | None = None) -> None: ...
    def set_text(self, text: str, timeout: float | None = None) -> None: ...

class Device:
    def __call__(self, **kwargs: str | list[str]) -> UiObject: ...
    @property
    def info(self) -> Mapping[str, str | int | bool | None]: ...
    @property
    def clipboard(self) -> str | None: ...
    def dump_hierarchy(self) -> str: ...
    def screenshot(self) -> Image.Image: ...
    def window_size(self) -> tuple[int, int]: ...
    def implicitly_wait(self, seconds: float | None = None) -> float: ...
    def app_list(self) -> list[str]: ...
    def app_current(self) -> Mapping[str, str]: ...
    def app_start(self, package_name: str, activity: str | None = None, stop: bool = False) -> None: ...
    def shell(self, cmdargs: str | list[str], timeout: float = 60) -> ShellResponse: ...
    def press(self, key: str) -> None: ...
    def swipe(self, fx: int, fy: int, tx: int, ty: int, duration: float | None = None) -> None: ...
    def click(self, x: int, y: int) -> None: ...

def connect(serial: str | None = None) -> Device: ...
