# Local type stubs: the uiautomator2 exceptions this project catches or raises in tests.
class BaseException(Exception): ...
class DeviceError(BaseException): ...
class HTTPError(DeviceError): ...
class UiAutomationError(DeviceError): ...
class LaunchUiAutomationError(UiAutomationError): ...
class RPCError(BaseException): ...
class NormalError(RPCError): ...
class UiObjectNotFoundError(NormalError): ...
